# Generated by Django 5.2.3 on 2025-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0002_alter_prato_tempo_preparo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prato',
            name='modo_preparo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prato',
            name='nome_prato',
            field=models.CharField(max_length=100),
        ),
    ]
