# Generated by Django 5.2.3 on 2025-06-28 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0003_alter_prato_categoria_alter_prato_modo_preparo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='data_prato',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
