# Generated by Django 5.2.3 on 2025-07-12 11:55

import churras.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0004_alter_prato_data_prato'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prato',
            old_name='data_prato',
            new_name='date_prato',
        ),
        migrations.AddField(
            model_name='prato',
            name='foto_prato',
            field=models.ImageField(blank=True, upload_to=churras.models.get_file_path),
        ),
        migrations.AddField(
            model_name='prato',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prato',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prato',
            name='modo_preparo',
            field=models.CharField(),
        ),
    ]
